### ISSUE TITLE
Add client setter for OAuthMiddleware and GrantTypeBase and make constructor argument optional

### ISSUE THREAD

**Issue by skafandri** [Sainsburys/guzzle-oauth2-plugin#10]
Currently `Sainsburys\Guzzle\Oauth2\GrantType\GrantTypeBase` and `Sainsburys\Guzzle\Oauth2\Middleware\OAuthMiddleware` accepts a `ClientInterface` in the constructor.
The client shouldn't be mandatory in the constructor and a `setClient` should be available.

The problem with the current design is that it prevents using this library with a Dependency Injection library (ie Symfony DI). If you need to create a Client that accepts a Middleware as arguments, and the middleware expects the Client as an argument too. None of the objects can be created (DI circular reference)

**Comment by dm** [comment]
Hi @skafandri, I've left Sainsbury's, but since the codebase that used `guzzle-oauth2-plugin` has been removed before that, I doubt there will be the need to maintain this internally. And since I've left the organisation, I can't fix/push changes to this either way.
Cheers,
Dan

**Comment by Tobion** [comment]
@skafandri you don't need to use the same guzzle client for the oauth part and the actual client. We solved this by just using different clients for the GrantType and the client that has the middleware. Then there is no ciruclar reference.

**Comment by skafandri** [comment]
I ended up using a different a client service for authentication too.
