### ISSUE TITLE
Help with additional examples

### ISSUE THREAD

**Issue by stevenscg** [Sainsburys/guzzle-oauth2-plugin#4]
This looks like a great implementation. Thanks for sharing!

Do you happen to have any additional examples?

I have one use case where the authorization service url and API url are different. I only had a few minutes with it yesterday, but was having problems updating a refresh token.

Another use case I have is where I already have an access_token stored in a database (etc) and just want to use the middleware to inject the token into the Authorization header of the requests. It seems like I just need to call `setAccessToken()`.

Finally, is there any way to be notified if the middleware had to get new tokens from the auth server during a request?

I'll be happy to add some color to these use cases as I get a chance to work with it further.

**Comment by chx** [comment]
While I managed to get AuthorizationCode workflow working https://github.com/Sainsburys/guzzle-oauth2-plugin/pull/6 I haven't managed to get the refresh token part working and have just written the raw Guzzle code https://gist.github.com/chx/78811d10b6186420ce36432aa98601ff

**Comment by dm** [comment]
I don't have any examples at hand; but the way to manage expiration/refresh is to use the `expires_in` and store that along with your token to know when you need to refresh it. Majority of services also allow you to check that expiration (and have a chance to refresh it) prior to attempting a request that might fail.
