### ISSUE TITLE
Is there a way to pass getAdditionalOptions?

### ISSUE THREAD

**Issue by altimea** [Sainsburys/guzzle-oauth2-plugin#7]
Hi

I need to pass ['verify' => false] to work on a dev environment and I found this function in the library which is intented for that, but how could I pass this array from my code?

**Comment by dm** [comment]
Hi,
The `getAdditionalOptions ` is currently not implemented as you're expecting (i.e. with `setAdditionalOptions`) but only for usage being overriden by JSON Web Token (JWT) Bearer.
But feel free to complement this implementation as you need, either extending the class and overriding the implementation; or we may consider PRs for either current patches (non-breaking changes) or for potentially new versions.
Thanks
